import type { LivestockApplicationStepId } from '@/features/livestock-application/types';

/** Kinyarwanda UI copy — never use as internal/database keys */
export const LIVESTOCK_FORM_LABELS = {
  formTitle: 'Ifishi y’ubwishingizi bw’amatungo',
  formSubtitle: 'Uzuza amakuru y’ifishi ya SONARWA mu buryo bwa digitale',
  saveDraft: 'Bika draft',
  submit: 'Ohereza ifishi',
  next: 'Komeza',
  previous: 'Subira inyuma',
  review: 'Suzuma',
  addLivestock: 'Ongeraho itungo',
  removeLivestock: 'Kuraho',
  uploadAnimals: 'Kurura Excel / CSV',
  downloadTemplate: 'Kuramo template',
  premiumAutoHint:
    'Igipimo (%) byujujwe ukurikije ubwoko bw’amatungo. Ikiguzi (100%), uruhare (60%/40%), n’amakomisiyo byibarwa mu buryo bwikora.',

  sections: {
    insurancePeriod: 'Igihe ubwishingizi bumara',
    applicantInfo: 'Amakuru y’usaba ubwishingizi',
    applicantAddress: 'Aho usaba ubwishingizi abarizwa',
    livestockLocation: 'Aho itungo riherereye',
    livestockDetails: 'Ibiranga amatungo',
    veterinarySupport: 'Amakuru y’ubuvuzi',
    diseaseInfo: 'Indwara n’ibyorezo',
    bankLoan: 'Amakuru y’inguzanyo',
    premiumInfo: 'Amakuru y’ubwishingizi',
    veterinaryVerification: 'Iyemezwa rya Veterineri',
    review: 'Suzuma ifishi',
  } satisfies Record<LivestockApplicationStepId, string>,

  fields: {
    policyStartDate: 'Kuva',
    policyEndDate: 'Kugeza',
    farmingExperience: 'Igihe amaze yorora',
    previousIncidents: 'Ibiza yaba yarahuye nabyo',
    ownerName: 'Amazina y’usaba ubwishingizi',
    isFirstApplication: 'Ni ubwa mbere',
    isRenewal: 'Ni ukongeresha',
    nationalId: 'Numero y’indangamuntu',
    ownerPhone: 'Numero ya telephone igendanwa',
    applicantProvince: 'Intara',
    applicantDistrict: 'Akarere',
    applicantSector: 'Umurenge',
    applicantCell: 'Akagari',
    applicantVillage: 'Umudugudu',
    livestockProvince: 'Intara',
    district: 'Akarere',
    sector: 'Umurenge',
    cell: 'Akagari',
    village: 'Umudugudu',
    animalType: 'Ubwoko bw’itungo',
    animalCategory: 'Icyiciro',
    animalAge: 'Imyaka',
    chipNumber: 'Eartag No / LOT No',
    breed: 'Ubwoko',
    color: 'Ibara',
    productivity: 'Umusaruro',
    sumAssured: 'Agaciro k’itungo',
    hasVeterinarian: 'Hari umuvuzi w’amatungo ubifitiye ubushobozi',
    veterinarianAvailability: 'Ubwitabire bw’umuvuzi',
    knownDiseases: 'Ni izihe ndwara/ibyorezo amatungo yawe ahura nabyo?',
    hasLoan: 'Hari ikigo cy’imari gifite inyungu muri iri tungo',
    financialInstitutionName: 'Izina rya Bank/MFI/SACCO',
    institutionLocation: 'Aho ibarizwa',
    loanAccountNumber: 'No ya konti',
    loanAmount: 'Inguzanyo (RWF)',
    premiumPercentage: 'Igipimo cy’ubwishingizi (%)',
    premiumRateAmount: 'Ikiguzi cy’ubwishingizi (100%)',
    farmerContributionAmount: 'Uruhare rw’umworozi (60%)',
    governmentContribution: 'Nkunganire (40%)',
    companyCommission: 'Komisiyo ya kampani (3.5%)',
    veterinaryCommission: 'Komisiyo ya Veterineri (10%)',
    insuranceAgentCode: 'Code y’umuhuza mu bwishingizi',
    veterinarianLicenseNumber: 'N° Licence ya Veterineri',
    veterinarianSignatureName: 'Amazina n’umukono',
  },

  placeholders: {
    ownerName: 'Urugero: BITWAYIKI Pierre Celestin',
    ownerPhone: '2507xxxxxxxx',
    nationalId: '1199080101234567',
    farmingExperience: 'Urugero: imyaka 5',
    chipNumber: '956000000000001',
    breed: 'Urugero: Fresian',
    color: 'Urugero: Black',
    productivity: 'Urugero: Milk',
    sumAssured: '700000',
    premiumPercentage: '5.5',
    premiumRateAmount: '38500',
    farmerContributionAmount: '23100',
    governmentContribution: '15400',
    companyCommission: '1348',
    veterinaryCommission: '3850',
    loanAmount: '500000',
    knownDiseases: 'Sobanura indwara cyangwa ibyorezo…',
    previousIncidents: 'Sobanura ibiza niba bihari…',
    financialInstitutionName: 'Izina rya banki',
    institutionLocation: 'Akarere / Umujyi',
    loanAccountNumber: 'Nomero ya konti',
    insuranceAgentCode: 'Code y’umuhuza',
    veterinarianLicenseNumber: 'Nomero ya licence',
    veterinarianSignatureName: 'Amazina yuzuye',
    animalAge: '3',
  },
} as const;

export const LIVESTOCK_APPLICATION_STEPS: { id: LivestockApplicationStepId; label: string }[] = [
  { id: 'insurancePeriod', label: LIVESTOCK_FORM_LABELS.sections.insurancePeriod },
  { id: 'applicantInfo', label: LIVESTOCK_FORM_LABELS.sections.applicantInfo },
  { id: 'applicantAddress', label: LIVESTOCK_FORM_LABELS.sections.applicantAddress },
  { id: 'livestockLocation', label: LIVESTOCK_FORM_LABELS.sections.livestockLocation },
  { id: 'livestockDetails', label: LIVESTOCK_FORM_LABELS.sections.livestockDetails },
  { id: 'veterinarySupport', label: LIVESTOCK_FORM_LABELS.sections.veterinarySupport },
  { id: 'diseaseInfo', label: LIVESTOCK_FORM_LABELS.sections.diseaseInfo },
  { id: 'bankLoan', label: LIVESTOCK_FORM_LABELS.sections.bankLoan },
  { id: 'premiumInfo', label: LIVESTOCK_FORM_LABELS.sections.premiumInfo },
  { id: 'veterinaryVerification', label: LIVESTOCK_FORM_LABELS.sections.veterinaryVerification },
  { id: 'review', label: LIVESTOCK_FORM_LABELS.sections.review },
];
