import type {
  InsuredLinePayload,
  LivestockApplicationListItem,
  LivestockApplicationPackage,
} from '@/features/livestock-application/domain/application-types';

/** Sample PDF for mock document previews */
export const MOCK_DOC_PDF =
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf';

function buildMockCattleLines(count: number): InsuredLinePayload[] {
  const breeds = ['Fresian', 'Cross', 'Ankole'];
  const categories = ['Imbyeyi', 'Imfizi'];
  return Array.from({ length: count }, (_, i) => {
    const sumAssured = 600_000 + (i % 5) * 50_000;
    const premiumRate = Math.round(sumAssured * 0.055);
    return {
      lineType: 'INDIVIDUAL' as const,
      quantity: 1,
      unitValue: sumAssured,
      sumAssured,
      premiumRate,
      farmerContribution: Math.round(premiumRate * 0.6),
      governmentContribution: Math.round(premiumRate * 0.4),
      animal: {
        species: 'Inka',
        chipNumber: `956000${String(i + 1).padStart(3, '0')}`,
        breed: breeds[i % breeds.length],
        animalCategory: categories[i % categories.length],
        animalAge: String(2 + (i % 4)),
        color: i % 2 === 0 ? 'Black & white' : 'Brown',
        productivity: i % 2 === 0 ? 'Milk' : 'Meat',
      },
      tekanaEligible: i % 7 === 0,
    };
  });
}

const MOCK_APP_001_LINES = buildMockCattleLines(24);
const MOCK_APP_001_TOTALS = MOCK_APP_001_LINES.reduce(
  (acc, line) => ({
    sumAssured: acc.sumAssured + line.sumAssured,
    premium: acc.premium + line.premiumRate,
    farmer: acc.farmer + line.farmerContribution,
    gov: acc.gov + line.governmentContribution,
  }),
  { sumAssured: 0, premium: 0, farmer: 0, gov: 0 },
);

/** Static samples for backend + UI — replace with GET /livestock/applications */
export const MOCK_LIVESTOCK_APPLICATIONS: LivestockApplicationListItem[] = [
  {
    _id: 'mock-app-001',
    applicationNumber: 'LS-2026-00041',
    insuranceProvider: 'SONARWA',
    speciesGroup: 'CATTLE',
    ownerMode: 'SINGLE_OWNER',
    status: 'PAYMENT_PROOF_REQUIRED',
    ownerSummary: 'BITWAYIKI Pierre Celestin',
    lineCount: 24,
    totals: { farmerContributionAmount: MOCK_APP_001_TOTALS.farmer, premiumRateAmount: MOCK_APP_001_TOTALS.premium },
    submittedAt: '2026-05-15T09:15:00.000Z',
    paymentProofStatus: 'PENDING',
    subsidyRequired: true,
  },
  {
    _id: 'mock-app-002',
    applicationNumber: 'LS-2026-00038',
    insuranceProvider: 'SONARWA',
    speciesGroup: 'POULTRY',
    ownerMode: 'SINGLE_OWNER',
    status: 'SUBSIDY_SECTOR_PENDING',
    ownerSummary: 'MUKAMANA Alice',
    lineCount: 2,
    totals: { farmerContributionAmount: 52_800, premiumRateAmount: 88_000 },
    submittedAt: '2026-05-12T14:22:00.000Z',
    paymentProofStatus: 'VERIFIED',
    subsidyRequired: true,
  },
  {
    _id: 'mock-app-003',
    applicationNumber: 'LS-2026-00035',
    insuranceProvider: 'SONARWA',
    speciesGroup: 'CATTLE',
    ownerMode: 'MULTI_OWNER',
    status: 'PENDING_COMMISSION_REVIEW',
    ownerSummary: '5 owners',
    lineCount: 3,
    totals: { farmerContributionAmount: 186_000, premiumRateAmount: 310_000 },
    submittedAt: '2026-05-08T11:00:00.000Z',
    paymentProofStatus: 'VERIFIED',
    subsidyRequired: true,
  },
  {
    _id: 'mock-app-004',
    applicationNumber: 'LS-2026-00029',
    insuranceProvider: 'SONARWA',
    speciesGroup: 'CATTLE',
    ownerMode: 'SINGLE_OWNER',
    status: 'INSURANCE_ISSUED',
    ownerSummary: 'NSENGIYUMVA Jean Bosco',
    lineCount: 3,
    totals: { farmerContributionAmount: 79_200, premiumRateAmount: 132_000 },
    submittedAt: '2026-05-02T16:45:00.000Z',
    paymentProofStatus: 'VERIFIED',
    subsidyRequired: false,
  },
];

export const MOCK_LIVESTOCK_APPLICATION_DETAILS: Record<string, LivestockApplicationPackage> = {
  'mock-app-001': {
    _id: 'mock-app-001',
    applicationNumber: 'LS-2026-00041',
    insuranceProvider: 'SONARWA',
    speciesGroup: 'CATTLE',
    ownerMode: 'SINGLE_OWNER',
    status: 'PAYMENT_PROOF_REQUIRED',
    submittedAt: '2026-05-15T09:15:00.000Z',
    updatedAt: '2026-05-15T09:15:00.000Z',
    vetId: 'vet-001',
    vetName: 'Dr. HABIMANA Eric',
    ownerSummary: 'BITWAYIKI Pierre Celestin',
    lineCount: 24,
    policyStartDate: '2026-04-01',
    policyEndDate: '2027-03-31',
    totals: {
      premiumPercentage: 5.5,
      premiumRateAmount: MOCK_APP_001_TOTALS.premium,
      farmerContributionAmount: MOCK_APP_001_TOTALS.farmer,
      governmentContribution: MOCK_APP_001_TOTALS.gov,
      companyCommission: Math.round(MOCK_APP_001_TOTALS.premium * 0.035),
      veterinaryCommission: Math.round(MOCK_APP_001_TOTALS.premium * 0.1),
      totalSumAssured: MOCK_APP_001_TOTALS.sumAssured,
    },
    paymentProof: { status: 'PENDING', expectedAmount: MOCK_APP_001_TOTALS.farmer },
    subsidyCase: { required: true, status: 'NOT_REQUIRED' },
    issuedDocuments: { invoice: MOCK_DOC_PDF },
    lines: MOCK_APP_001_LINES,
  },
  'mock-app-002': {
    _id: 'mock-app-002',
    applicationNumber: 'LS-2026-00038',
    insuranceProvider: 'SONARWA',
    speciesGroup: 'POULTRY',
    ownerMode: 'SINGLE_OWNER',
    poultryProductType: 'EGG_LAYER',
    status: 'SUBSIDY_SECTOR_PENDING',
    submittedAt: '2026-05-12T14:22:00.000Z',
    updatedAt: '2026-05-13T08:00:00.000Z',
    vetId: 'vet-001',
    vetName: 'Dr. HABIMANA Eric',
    ownerSummary: 'MUKAMANA Alice',
    lineCount: 2,
    policyStartDate: '2026-03-15',
    policyEndDate: '2027-03-14',
    totals: {
      premiumPercentage: 5.5,
      premiumRateAmount: 88_000,
      farmerContributionAmount: 52_800,
      governmentContribution: 35_200,
      companyCommission: 3_080,
      veterinaryCommission: 8_800,
      totalSumAssured: 1_600_000,
    },
    paymentProof: {
      status: 'VERIFIED',
      expectedAmount: 52_800,
      documentUrl: MOCK_DOC_PDF,
      transactionId: 'MOMO-20260512-88421',
      submittedAt: '2026-05-12T15:00:00.000Z',
      verifiedAt: '2026-05-13T07:30:00.000Z',
    },
    subsidyCase: {
      required: true,
      status: 'SECTOR_PENDING',
      generatedDocumentUrl: MOCK_DOC_PDF,
    },
    lines: [
      {
        lineType: 'LOT',
        quantity: 200,
        unitValue: 4_000,
        sumAssured: 800_000,
        premiumRate: 44_000,
        farmerContribution: 26_400,
        governmentContribution: 17_600,
        animal: {
          species: 'Inkoko',
          productivity: 'EGG_LAYER',
          hatcherySource: 'Kigali Hatchery Ltd',
          poultryProductType: 'EGG_LAYER',
        },
        tekanaEligible: false,
      },
      {
        lineType: 'LOT',
        quantity: 200,
        unitValue: 4_000,
        sumAssured: 800_000,
        premiumRate: 44_000,
        farmerContribution: 26_400,
        governmentContribution: 17_600,
        animal: {
          species: 'Inkoko',
          productivity: 'EGG_LAYER',
          hatcherySource: 'Musanze Poultry Farm',
          poultryProductType: 'EGG_LAYER',
        },
        tekanaEligible: false,
      },
    ],
  },
  'mock-app-003': {
    _id: 'mock-app-003',
    applicationNumber: 'LS-2026-00035',
    insuranceProvider: 'SONARWA',
    speciesGroup: 'CATTLE',
    ownerMode: 'MULTI_OWNER',
    status: 'PENDING_COMMISSION_REVIEW',
    submittedAt: '2026-05-08T11:00:00.000Z',
    updatedAt: '2026-05-10T10:00:00.000Z',
    vetId: 'vet-001',
    vetName: 'Dr. HABIMANA Eric',
    ownerSummary: '5 owners',
    lineCount: 3,
    policyStartDate: '2026-04-01',
    policyEndDate: '2027-03-31',
    totals: {
      premiumPercentage: 5.5,
      premiumRateAmount: 310_000,
      farmerContributionAmount: 186_000,
      governmentContribution: 124_000,
      companyCommission: 10_850,
      veterinaryCommission: 31_000,
      totalSumAssured: 5_636_364,
    },
    paymentProof: {
      status: 'VERIFIED',
      expectedAmount: 186_000,
      documentUrl: MOCK_DOC_PDF,
      transactionId: 'BK-TRX-20260508-9912',
      verifiedAt: '2026-05-09T09:00:00.000Z',
    },
    subsidyCase: {
      required: true,
      status: 'SONARWA_APPROVED',
      generatedDocumentUrl: MOCK_DOC_PDF,
      uploadedSignedDocumentUrl: MOCK_DOC_PDF,
      sectorSignedAt: '2026-05-09T12:00:00.000Z',
      vetSignedAt: '2026-05-09T14:00:00.000Z',
      sonarwaApprovedAt: '2026-05-10T10:00:00.000Z',
    },
    lines: [
      {
        lineType: 'INDIVIDUAL',
        quantity: 1,
        unitValue: 700_000,
        sumAssured: 700_000,
        premiumRate: 38_500,
        farmerContribution: 23_100,
        governmentContribution: 15_400,
        owner: { name: 'UWIMANA Claude', phone: '250788123456' },
        animal: { species: 'Inka', chipNumber: '956000010', breed: 'Cross', animalCategory: 'Imbyeyi' },
        tekanaEligible: false,
      },
      {
        lineType: 'INDIVIDUAL',
        quantity: 1,
        unitValue: 680_000,
        sumAssured: 680_000,
        premiumRate: 37_400,
        farmerContribution: 22_440,
        governmentContribution: 14_960,
        owner: { name: 'NYIRABAZUNGU Marie', phone: '250789654321' },
        animal: { species: 'Inka', chipNumber: '956000011', breed: 'Fresian', animalCategory: 'Imbyeyi' },
        tekanaEligible: false,
      },
      {
        lineType: 'INDIVIDUAL',
        quantity: 1,
        unitValue: 620_000,
        sumAssured: 620_000,
        premiumRate: 34_100,
        farmerContribution: 20_460,
        governmentContribution: 13_640,
        owner: { name: 'HABIMANA Eric', phone: '250788999888' },
        animal: { species: 'Inka', chipNumber: '956000012', breed: 'Ankole', animalCategory: 'Imfizi' },
        tekanaEligible: false,
      },
    ],
  },
  'mock-app-004': {
    _id: 'mock-app-004',
    applicationNumber: 'LS-2026-00029',
    insuranceProvider: 'SONARWA',
    speciesGroup: 'CATTLE',
    ownerMode: 'SINGLE_OWNER',
    status: 'INSURANCE_ISSUED',
    submittedAt: '2026-05-02T16:45:00.000Z',
    updatedAt: '2026-05-03T08:00:00.000Z',
    vetId: 'vet-001',
    vetName: 'Dr. HABIMANA Eric',
    ownerSummary: 'NSENGIYUMVA Jean Bosco',
    lineCount: 3,
    policyStartDate: '2026-03-01',
    policyEndDate: '2027-02-28',
    totals: {
      premiumPercentage: 5.5,
      premiumRateAmount: 132_000,
      farmerContributionAmount: 79_200,
      governmentContribution: 52_800,
      companyCommission: 4_620,
      veterinaryCommission: 13_200,
      totalSumAssured: 2_400_000,
    },
    paymentProof: {
      status: 'VERIFIED',
      expectedAmount: 79_200,
      documentUrl: MOCK_DOC_PDF,
      transactionId: 'MOMO-20260502-44102',
      verifiedAt: '2026-05-02T18:00:00.000Z',
    },
    subsidyCase: { required: false, status: 'NOT_REQUIRED' },
    issuedDocuments: {
      invoice: MOCK_DOC_PDF,
      insuranceCertificate: MOCK_DOC_PDF,
      contract: MOCK_DOC_PDF,
      receipt: MOCK_DOC_PDF,
      ebm: MOCK_DOC_PDF,
    },
    lines: [
      {
        lineType: 'INDIVIDUAL',
        quantity: 1,
        unitValue: 800_000,
        sumAssured: 800_000,
        premiumRate: 44_000,
        farmerContribution: 26_400,
        governmentContribution: 17_600,
        animal: { species: 'Inka', chipNumber: '956999001', breed: 'Fresian', animalCategory: 'Imbyeyi' },
        tekanaEligible: true,
      },
      {
        lineType: 'INDIVIDUAL',
        quantity: 1,
        unitValue: 800_000,
        sumAssured: 800_000,
        premiumRate: 44_000,
        farmerContribution: 26_400,
        governmentContribution: 17_600,
        animal: { species: 'Inka', chipNumber: '956999002', breed: 'Cross', animalCategory: 'Imfizi' },
        tekanaEligible: true,
      },
      {
        lineType: 'INDIVIDUAL',
        quantity: 1,
        unitValue: 800_000,
        sumAssured: 800_000,
        premiumRate: 44_000,
        farmerContribution: 26_400,
        governmentContribution: 17_600,
        animal: { species: 'Inka', chipNumber: '956999003', breed: 'Ankole', animalCategory: 'Imbyeyi' },
        tekanaEligible: true,
      },
    ],
  },
};
